# Tensor(张量)
- 标量(Scalar)是只有大小没有方向的量;标量相当于一个矩阵中的一个元素,是零维的
- 向量(Vector)是有大小和方向的量;向量相当于矩阵的一列或一行,俗称行向量,列向量,是一维的
- 矩阵(Matrix)是多个向量排在一起的一堆量;多个向量的组合,是二维的
- 张量(Tensor)其实是值任意维度数字的组合,可以说矩阵是一个面,张量就是一个立方体,矩阵是其中一个面;张量可以是任何的维度的
- --

In [1]:
import torch

In [2]:
x=torch.Tensor(3,4)  # 没有初始化这个3*4的矩阵,但其中仍然有值

In [3]:
y=torch.Tensor(4,2,3)  # 构造了一个4*2*3的张量,仍然没有初始化,里面也有值
y


(0 ,.,.) = 
  0.0000e+00  0.0000e+00  1.3476e+32
  4.2039e-45  3.2267e+04  4.5722e-41

(1 ,.,.) = 
  8.4078e-45  4.5722e-41  1.5749e+17
  1.2612e-44  2.3335e+28  4.5722e-41

(2 ,.,.) = 
  1.6816e-44  4.5722e-41  4.9665e+32
  2.1019e-44  4.9666e+32  4.5722e-41

(3 ,.,.) = 
  2.5223e-44  4.5722e-41  4.9666e+32
  2.9427e-44  4.9667e+32  4.5722e-41
[torch.FloatTensor of size 4x2x3]

#### 上面的张量表示4个2*3的矩阵构成

#### 构建随机初始化的张量

In [4]:
x=torch.rand(3,4)
x


 0.6248  0.1905  0.0411  0.7426
 0.9412  0.8381  0.7607  0.0780
 0.7446  0.9294  0.4533  0.8594
[torch.FloatTensor of size 3x4]

In [5]:
y=torch.rand(4,2,3)
y


(0 ,.,.) = 
  0.1530  0.7118  0.2302
  0.2192  0.9852  0.0978

(1 ,.,.) = 
  0.9087  0.2802  0.7886
  0.1079  0.9140  0.2991

(2 ,.,.) = 
  0.7756  0.8042  0.8952
  0.9353  0.0762  0.7949

(3 ,.,.) = 
  0.7323  0.4031  0.8450
  0.4743  0.6642  0.3241
[torch.FloatTensor of size 4x2x3]

#### 构建全1的初始化的张量

In [6]:
a=torch.ones(5)
print(a)
a=torch.ones(2,3)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]


 1  1  1
 1  1  1
[torch.FloatTensor of size 2x3]



#### numpy的数组使用shape属性可得到维度信息,tensor使用x.size()方法来得到维度信息

In [7]:
print(x.size())
print(y.size())

torch.Size([3, 4])
torch.Size([4, 2, 3])


## 对于tensor的数学运算
- 不单单限制于加法

In [8]:
# 加法
x=torch.rand(4,5)
y=torch.rand(4,5)
print(x)
print(y)


 0.0659  0.2777  0.8814  0.1489  0.0108
 0.5029  0.5599  0.4443  0.0429  0.5086
 0.1356  0.2575  0.5391  0.0296  0.1309
 0.0941  0.5383  0.7847  0.7284  0.5474
[torch.FloatTensor of size 4x5]


 0.0132  0.1055  0.6988  0.6686  0.2953
 0.9486  0.6711  0.0123  0.7753  0.3579
 0.4538  0.2485  0.5345  0.4622  0.8066
 0.2614  0.7342  0.8567  0.2894  0.7178
[torch.FloatTensor of size 4x5]



In [9]:
x+y  # 矩阵加法,每个矩阵的维度要相同,然后对应的元素相加


 0.0791  0.3832  1.5802  0.8175  0.3061
 1.4515  1.2310  0.4566  0.8182  0.8665
 0.5894  0.5060  1.0736  0.4918  0.9375
 0.3556  1.2725  1.6415  1.0178  1.2652
[torch.FloatTensor of size 4x5]

In [10]:
torch.add(x,y)  # 效果同上


 0.0791  0.3832  1.5802  0.8175  0.3061
 1.4515  1.2310  0.4566  0.8182  0.8665
 0.5894  0.5060  1.0736  0.4918  0.9375
 0.3556  1.2725  1.6415  1.0178  1.2652
[torch.FloatTensor of size 4x5]

In [11]:
result=torch.Tensor(4,5)  # 提供一个输出作为操作
torch.add(x,y,out=result)
result


 0.0791  0.3832  1.5802  0.8175  0.3061
 1.4515  1.2310  0.4566  0.8182  0.8665
 0.5894  0.5060  1.0736  0.4918  0.9375
 0.3556  1.2725  1.6415  1.0178  1.2652
[torch.FloatTensor of size 4x5]

In [12]:
x.add_(y)  # 就地操作,前面的变量直接被赋值两个变量的运算结果
print(x)
print(y)


 0.0791  0.3832  1.5802  0.8175  0.3061
 1.4515  1.2310  0.4566  0.8182  0.8665
 0.5894  0.5060  1.0736  0.4918  0.9375
 0.3556  1.2725  1.6415  1.0178  1.2652
[torch.FloatTensor of size 4x5]


 0.0132  0.1055  0.6988  0.6686  0.2953
 0.9486  0.6711  0.0123  0.7753  0.3579
 0.4538  0.2485  0.5345  0.4622  0.8066
 0.2614  0.7342  0.8567  0.2894  0.7178
[torch.FloatTensor of size 4x5]



#### 可以使用类似Numpy的索引操作Tensor

In [13]:
print(x)
print(x[1])  # 注意其得到的是一个向量一维的
print(x[:1])  # 这样得到的就是一个二维的矩阵,一个行向量
print(x[:,2]) # 得到的是第几列的列向量
print(x[1:3])  # 切片是操作是取行
print(x[1:3,2])  # 得到索引为1,2的行向量组成的矩阵的索引为2列


 0.0791  0.3832  1.5802  0.8175  0.3061
 1.4515  1.2310  0.4566  0.8182  0.8665
 0.5894  0.5060  1.0736  0.4918  0.9375
 0.3556  1.2725  1.6415  1.0178  1.2652
[torch.FloatTensor of size 4x5]


 1.4515
 1.2310
 0.4566
 0.8182
 0.8665
[torch.FloatTensor of size 5]


 0.0791  0.3832  1.5802  0.8175  0.3061
[torch.FloatTensor of size 1x5]


 1.5802
 0.4566
 1.0736
 1.6415
[torch.FloatTensor of size 4]


 1.4515  1.2310  0.4566  0.8182  0.8665
 0.5894  0.5060  1.0736  0.4918  0.9375
[torch.FloatTensor of size 2x5]


 0.4566
 1.0736
[torch.FloatTensor of size 2]



## 改变Tensor的大小


In [14]:
# 使用torch.view
x=torch.randn(4,4)
y=x.view(16)
z=x.view(-1,8)  # 参数中-1代表自动填充,根据另一个维度来自动计算这里填充多少

In [15]:
print(x)
print(y)
print(z)


-0.7003 -0.6439 -0.7151  2.4373
 0.4446 -0.2303  1.4013  0.0968
 1.1311 -1.3672 -1.1029  1.4991
 0.4934 -0.0628  0.0920 -0.6678
[torch.FloatTensor of size 4x4]


-0.7003
-0.6439
-0.7151
 2.4373
 0.4446
-0.2303
 1.4013
 0.0968
 1.1311
-1.3672
-1.1029
 1.4991
 0.4934
-0.0628
 0.0920
-0.6678
[torch.FloatTensor of size 16]


-0.7003 -0.6439 -0.7151  2.4373  0.4446 -0.2303  1.4013  0.0968
 1.1311 -1.3672 -1.1029  1.4991  0.4934 -0.0628  0.0920 -0.6678
[torch.FloatTensor of size 2x8]



## Tensor------>Numpy

In [16]:
x=torch.ones(5)
print(x)
y=x.numpy()
print(y)
print(y.shape)
print('===========================')
x=torch.ones(5,1)  # 这里维度的不同对转换为numpy的结果的影响是不同的
print(x)
y=x.numpy()
print(y)
print(y.shape)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]

[1. 1. 1. 1. 1.]
(5,)

 1
 1
 1
 1
 1
[torch.FloatTensor of size 5x1]

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]
(5, 1)


In [17]:
a=torch.ones(5)
b=a.numpy()
a.add_(2)
print(a)
print(b)
# 证明了torch的tensor与numpy的ndarray共用一个内存空间


 3
 3
 3
 3
 3
[torch.FloatTensor of size 5]

[3. 3. 3. 3. 3.]


## Numpy------------->Tensor

In [18]:
import numpy as np
a=np.ones(5)
b=torch.from_numpy(a)
print(a)
print(b)
print('========================')
# 这里同样说明Numpy与Tensor共用内存空间
np.add(a,2,out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]

 1
 1
 1
 1
 1
[torch.DoubleTensor of size 5]

[3. 3. 3. 3. 3.]

 3
 3
 3
 3
 3
[torch.DoubleTensor of size 5]

